### ISSUE TITLE
Unexpected behavior with touch logo

### ISSUE THREAD

**Issue by ngammarano** [microbit-foundation/pxt-microbit-v2-extension#20]
I have programmed a micro:bit V2 with [this program](https://makecode.microbit.org/_P1hCi4TJRgrC) using [MakeCode editor version beta](https://makecode.microbit.org/beta). Micro:bit should show a check mark on logo pressed and show a cross mark on logo released.
The behavior I am experiencing is that when I touch the logo but I do not release it, nothing happens.
When I release the logo, a cross mark appears first, then a check mark appears.

Is this a bug or I am misunderstanding blocks "on logo pressed" and "on logo released"?

**Comment by narongporn** [comment]
All pressed events behave the same way since previous version of makecode.

On button pressed, on pin pressed, on logo pressed occurred after you press and released. Not when you first press it.

**Comment by ngammarano** [comment]
You are right. I got confused because I took "pressed" as the opposite of "release".
Besides, the way it is now events "pressed" and "released" act **almost** the same way as both occur when releasing the button (the difference is that if you press the button/logo for a long time, only the "release" event occurs, but when there is a "press" event, there is always a "release" event).

Maybe it would be better to call something like "on button state changed (pressed to released)" instead of the current "on button released"?

**Comment by microbit-mark** [comment]
@ngammarano Work on these blocks i progressing rapidly and you'll now see options for the logo press events in the block. <img width="342" alt="image" src="https://user-images.githubusercontent.com/31242877/97416336-35e6a580-18fe-11eb-8ede-bd3dd2fa0a86.png">

To view the latest updates, you will need to use this alpha editor URL https://makecode.microbit.org/v3.1#editor which includes the blocks by default.

They are not currently part of this extension.
