### ISSUE TITLE
Resolve language and blocks for logo touch/press/release

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/pxt-microbit-v2-extension#4]
This has two elements.

1. What are the events we use - is it 'touched' and 'released' or 'pressed' and 'released'
2. Can we have a single block with dropdown (eg like the shake block) instead of two blocks

I know @microbit-giles you're expecting teacher feedback this week.

**Comment by ngammarano** [comment]
> This has two elements.
> 
> 1. What are the events we use - is it 'touched' and 'released' or 'pressed' and 'released'
> 2. Can we have a single block with dropdown (eg like the shake block) instead of two blocks
> 
> I know @microbit-giles you're expecting teacher feedback this week.

This has been addressed. See [this project](https://makecode.microbit.org/_L6rC79h9zcYD) (you have to open it with [MakeCode editor beta version](https://makecode.microbit.org/beta)).

**Comment by microbit-matt-hillsdon** [comment]
Closing as this is now being addressed as part of moving the blocks from this extension to MakeCode.
