### ISSUE TITLE
Block discovery after adding extension

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/pxt-microbit-v2-extension#5]
This point was raised by Abhijith during the MakeCode call today, but is something we've all discussed a bit too...

The way we're currently adding blocks into the cateogries makes it relatively hard for a user to answer the questions
* "Which blocks did that extension add?"
* "Which blocks do I need NOT to use so this program can work on a v2"

One nice thing about adding them into the categories is that it doesn't break up the normal 'exploration' flow. However, Abhijith was trying to work out "what are all the new things I can do". I think we can probably address this with documentation, but not totally sure if thats the right approach.

@microbit-giles has anyone raised this with you yet? What do you think?

I would say at the least, we should do the following
* Make sure 'input' blocks go into categories inside the 'input' menu, so "Microphone" and "Logo"
* For Music blocks, think of an appropriate category, perhaps "Speaker" and make both the 'disable' and 'sound emoji' blocks part of that category?

I don't mind adding things into pins, it's an advanced block

J

**Comment by microbit-matt-hillsdon** [comment]
Current approach inside MakeCode is a "microbit v2" group inside the various top-level namespaces.

This issue isn't a good place for further discussion now that the implementation has moved (and I'll archive this repository shortly).

Closing.
